# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-Received
version:      1.00
version_from: lib/Email/Received.pm
installdirs:  site
requires:
    Regexp::Common:                0
    Text::Balanced:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
